/**
 * Contributor Revshare — payout models for verified platform contributors.
 * Covers bounties, report revenue sharing, verification queue payments,
 * source-curation stipends, and the editor tier.
 *
 * Моделі виплат для верифікованих контрибʼюторів платформи.
 * Охоплює баунті, розподіл доходу від звітів, оплату черги верифікації,
 * стипендію за курацію джерел та редакторський рівень.
 */

// ── Types ──────────────────────────────────────────────────────────────────────

/**
 * Contribution type identifiers for each payout model.
 * Ідентифікатори типів внеску для кожної моделі виплат.
 */
export type ContributionType =
  | "bounty"
  | "report-revshare"
  | "verification-queue"
  | "source-curation-stipend"
  | "editor-tier";

// ── Interfaces ─────────────────────────────────────────────────────────────────

/**
 * Describes a single contributor payout model.
 * Описує одну модель виплат контрибʼютору.
 */
export interface ContributorPayoutModel {
  /** Machine-readable identifier */
  id: ContributionType;

  /** Contribution type (mirrors id for API clarity) */
  type: ContributionType;

  /** Display name — English */
  name_en: string;

  /** Display name — Ukrainian */
  name_uk: string;

  /**
   * Human-readable rate description (USD amounts / ranges / frequency).
   * Опис ставки у вільній формі (суми в USD / діапазони / частота).
   */
  rateUsd: string;

  /** Additional operational notes — English */
  notes_en: string;

  /** Additional operational notes — Ukrainian */
  notes_uk: string;
}

// ── Payout models ──────────────────────────────────────────────────────────────

/**
 * All five contributor payout models supported by the platform.
 * Усі п'ять моделей виплат контрибʼюторам, підтримуваних платформою.
 */
export const CONTRIBUTOR_PAYOUT_MODELS: ContributorPayoutModel[] = [
  {
    id: "bounty",
    type: "bounty",
    name_en: "Bounties",
    name_uk: "Баунті",
    rateUsd: "$5–$500 per task",
    notes_en:
      "Per-task payment for discrete OSINT contributions: solve a geolocation, verify a video clip, translate a Telegram channel, or identify an entity. Rate scales with task complexity and priority.",
    notes_uk:
      "Оплата за окреме завдання: геолокація, верифікація відеокліпу, переклад Telegram-каналу або ідентифікація сутності. Ставка залежить від складності та пріоритету завдання.",
  },
  {
    id: "report-revshare",
    type: "report-revshare",
    name_en: "Report Revenue Share",
    name_uk: "Розподіл доходу від звітів",
    rateUsd: "30–50% of individual report revenue",
    notes_en:
      "Bylined contributors on published intelligence reports receive 30–50% of the revenue generated by that report (single-purchase and subscription attribution). Percentage depends on contribution depth and editorial involvement.",
    notes_uk:
      "Контрибʼютори, зазначені як автори опублікованих звітів, отримують 30–50% доходу від звіту (разові покупки та підписна атрибуція). Відсоток залежить від глибини внеску та редакторської залученості.",
  },
  {
    id: "verification-queue",
    type: "verification-queue",
    name_en: "Verification Queue Payments",
    name_uk: "Оплата черги верифікації",
    rateUsd: "Per verified item — tiered by complexity",
    notes_en:
      "Contributors who process items in the verification queue are compensated per verified item. Three complexity tiers: basic (binary true/false check), standard (multi-source cross-reference), and advanced (geospatial or forensic analysis required).",
    notes_uk:
      "Контрибʼютори, що обробляють елементи черги верифікації, отримують оплату за кожен верифікований елемент. Три рівні складності: базовий (бінарна перевірка), стандартний (перехресна перевірка з кількох джерел) та розширений (геопросторовий або криміналістичний аналіз).",
  },
  {
    id: "source-curation-stipend",
    type: "source-curation-stipend",
    name_en: "Source-Curation Stipend",
    name_uk: "Стипендія за курацію джерел",
    rateUsd: "$50–$500 / month",
    notes_en:
      "Monthly stipend for contributors who maintain a vetted source list for a specific region, topic, or language. Rate depends on source list size, freshness cadence, and domain specialty.",
    notes_uk:
      "Щомісячна стипендія для контрибʼюторів, які підтримують перевірений список джерел для конкретного регіону, теми або мови. Ставка залежить від обсягу списку, частоти оновлень та спеціалізації.",
  },
  {
    id: "editor-tier",
    type: "editor-tier",
    name_en: "Editor Tier",
    name_uk: "Редакторський рівень",
    rateUsd: "Hourly rate — market rate for senior OSINT editorial review",
    notes_en:
      "Long-term, high-reputation contributors may be contracted as editors. Paid hourly for reviewing and improving reports, training junior contributors, and maintaining editorial standards.",
    notes_uk:
      "Довгострокові контрибʼютори з високою репутацією можуть бути залучені як редактори. Погодинна оплата за рецензування та покращення звітів, навчання молодших контрибʼюторів та дотримання редакційних стандартів.",
  },
];

// ── Policy notes ───────────────────────────────────────────────────────────────

/** Reputation gate — English */
export const CONTRIBUTOR_REP_GATE_NOTE_EN =
  'Contributors must reach the "Verified Contributor" reputation score before any payout is processed. Reputation is earned through verified contributions reviewed by senior analysts.';

/** Reputation gate — Ukrainian */
export const CONTRIBUTOR_REP_GATE_NOTE_UK =
  'Перед обробкою будь-якої виплати контрибʼютор повинен досягти рівня репутації "Верифікований контрибʼютор". Репутація нараховується за верифіковані внески, перевірені старшими аналітиками.';

/** Stripe Connect KYC — English */
export const STRIPE_CONNECT_KYC_NOTE_EN =
  "All payouts are processed via Stripe Connect. Contributors must complete KYC (Know Your Customer) identity verification before receiving any payment. Stripe Connect Express accounts are used for cross-border payouts.";

/** Stripe Connect KYC — Ukrainian */
export const STRIPE_CONNECT_KYC_NOTE_UK =
  "Усі виплати обробляються через Stripe Connect. Контрибʼютори зобовʼязані пройти KYC (верифікацію особи) перед отриманням будь-якої виплати. Для транскордонних переказів використовуються облікові записи Stripe Connect Express.";

/** Anti-collusion — English */
export const ANTI_COLLUSION_NOTE_EN =
  "The platform employs automated sockpuppet and collusion detection. Accounts sharing device fingerprints, IP ranges, or payment methods, or submitting correlated low-quality work, will be flagged and removed from payout eligibility pending investigation.";

/** Anti-collusion — Ukrainian */
export const ANTI_COLLUSION_NOTE_UK =
  "Платформа використовує автоматичне виявлення sockpuppet-акаунтів та змови. Акаунти зі спільними відбитками пристроїв, IP-діапазонами або платіжними методами, а також ті, що подають корельовану неякісну роботу, будуть позначені та виключені з виплат до завершення розслідування.";

/** Quality audit — English */
export const QUALITY_AUDIT_NOTE_EN =
  "A random sample of completed contributor work is re-verified by a senior analyst each month. Systematic errors or misrepresentations result in payout clawback and reputation penalty. Persistent quality failures lead to tier demotion or removal.";

/** Quality audit — Ukrainian */
export const QUALITY_AUDIT_NOTE_UK =
  "Щомісяця старший аналітик повторно верифікує випадкову вибірку виконаної контрибʼюторами роботи. Систематичні помилки або фальсифікації призводять до повернення виплат та штрафу репутації. Постійні порушення якості ведуть до пониження рівня або видалення.";

/** Tax forms — English */
export const TAX_FORM_NOTE_EN =
  "Contributors who earn $600 or more in a calendar year (US persons) will receive a 1099-NEC. Non-US contributors are subject to equivalent tax documentation requirements in their jurisdiction. All contributors must provide valid tax information before payouts begin.";

/** Tax forms — Ukrainian */
export const TAX_FORM_NOTE_UK =
  "Контрибʼютори, які заробили 600 USD або більше в календарному році (особи з США), отримають форму 1099-NEC. До контрибʼюторів з інших країн застосовуються відповідні вимоги щодо податкової документації їхньої юрисдикції. Усі контрибʼютори зобовʼязані надати дійсні податкові дані перед початком виплат.";

/** Investment philosophy — English */
export const CONTRIBUTOR_INVESTMENT_NOTE_EN =
  "Contributor payments are an investment in platform supply quality — not a cost-cutting measure. The platform pays market rates to attract and retain skilled contributors, recognising that high-quality OSINT supply is the core competitive advantage of the intelligence product.";

/** Investment philosophy — Ukrainian */
export const CONTRIBUTOR_INVESTMENT_NOTE_UK =
  "Виплати контрибʼюторам — це інвестиція в якість постачання платформи, а не засіб скорочення витрат. Платформа платить ринкові ставки для залучення та утримання кваліфікованих контрибʼюторів, визнаючи, що якісне OSINT-постачання є основною конкурентною перевагою розвідувального продукту.";

// ── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Compute the contributor payout for a single report based on its revenue
 * and the agreed revshare percentage.
 *
 * Обчислює виплату контрибʼютору за звіт на основі доходу та відсотка розподілу.
 *
 * @param reportRevenueUsd   Total gross revenue attributed to the report (USD).
 * @param revsharePercent    Revshare fraction 0–1 (e.g. 0.40 for 40%).
 * @returns contributorPayoutUsd  Contributor payout amount in USD, rounded to 2 dp.
 */
export function computeReportRevshare(
  reportRevenueUsd: number,
  revsharePercent: number,
): number {
  if (reportRevenueUsd < 0 || revsharePercent < 0 || revsharePercent > 1) {
    throw new RangeError(
      "reportRevenueUsd must be ≥ 0 and revsharePercent must be between 0 and 1.",
    );
  }
  return Math.round(reportRevenueUsd * revsharePercent * 100) / 100;
}
