/**
 * Aegis Lens — Subcategory Registry
 * One entry per named subcategory across all 10 top-level domains.
 * Every entry is a programmatic hub URL (Phase 1). Phase 2 builds micro-category files.
 */

import type { Subcategory } from "./types";

export const SUBCATEGORIES: Subcategory[] = [
  // ── Military & Defense ─────────────────────────────────────────────────────
  {
    id: "military-drones",
    parentDomain: "Military & Defense",
    name_en: "Drones",
    name_uk: "Дрони",
    slugPrefix: "military/drones",
    isProgrammaticHub: true,
    exampleSlugs: ["fpv-drone-battlefield-use", "shahed-kamikaze-drone-attacks"],
  },
  {
    id: "military-missiles",
    parentDomain: "Military & Defense",
    name_en: "Missiles",
    name_uk: "Ракети",
    slugPrefix: "military/missiles",
    isProgrammaticHub: true,
    exampleSlugs: ["iskander-missile-strikes", "storm-shadow-ukraine-deployment"],
  },
  {
    id: "military-artillery",
    parentDomain: "Military & Defense",
    name_en: "Artillery",
    name_uk: "Артилерія",
    slugPrefix: "military/artillery",
    isProgrammaticHub: true,
    exampleSlugs: ["howitzer-identification-guide", "artillery-cluster-munitions-use"],
  },
  {
    id: "military-armor",
    parentDomain: "Military & Defense",
    name_en: "Armor",
    name_uk: "Бронетехніка",
    slugPrefix: "military/armor",
    isProgrammaticHub: true,
    exampleSlugs: ["t-90-tank-losses-ukraine", "bradley-ifv-ukraine-operations"],
  },
  {
    id: "military-air-defense",
    parentDomain: "Military & Defense",
    name_en: "Air Defense",
    name_uk: "Протиповітряна оборона",
    slugPrefix: "military/air-defense",
    isProgrammaticHub: true,
    exampleSlugs: ["patriot-system-ukraine-deployment", "s-300-battery-tracking"],
  },
  {
    id: "military-naval",
    parentDomain: "Military & Defense",
    name_en: "Naval",
    name_uk: "Морські сили",
    slugPrefix: "military/naval",
    isProgrammaticHub: true,
    exampleSlugs: ["black-sea-fleet-losses", "naval-drone-attack-documentation"],
  },
  {
    id: "military-special-ops",
    parentDomain: "Military & Defense",
    name_en: "Special Operations",
    name_uk: "Спецоперації",
    slugPrefix: "military/special-ops",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-gur-operations-analysis", "sabotage-behind-enemy-lines"],
  },
  {
    id: "military-logistics",
    parentDomain: "Military & Defense",
    name_en: "Logistics",
    name_uk: "Логістика",
    slugPrefix: "military/logistics",
    isProgrammaticHub: true,
    exampleSlugs: ["russian-supply-chain-analysis", "nato-aid-delivery-tracking"],
  },
  {
    id: "military-training",
    parentDomain: "Military & Defense",
    name_en: "Training",
    name_uk: "Підготовка",
    slugPrefix: "military/training",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-nato-training-programs", "russian-mobilisation-training"],
  },
  {
    id: "military-recruitment",
    parentDomain: "Military & Defense",
    name_en: "Recruitment",
    name_uk: "Рекрутинг",
    slugPrefix: "military/recruitment",
    isProgrammaticHub: true,
    exampleSlugs: ["russian-mobilisation-tracking", "wagner-group-recruitment-africa"],
  },

  // ── Infrastructure ─────────────────────────────────────────────────────────
  {
    id: "infra-energy",
    parentDomain: "Infrastructure",
    name_en: "Energy",
    name_uk: "Енергетика",
    slugPrefix: "infrastructure/energy",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-power-grid-attacks", "nuclear-plant-monitoring"],
  },
  {
    id: "infra-telecom",
    parentDomain: "Infrastructure",
    name_en: "Telecom",
    name_uk: "Телекомунікації",
    slugPrefix: "infrastructure/telecom",
    isProgrammaticHub: true,
    exampleSlugs: ["starlink-ukraine-coverage", "internet-outages-conflict-zones"],
  },
  {
    id: "infra-transport",
    parentDomain: "Infrastructure",
    name_en: "Transport",
    name_uk: "Транспорт",
    slugPrefix: "infrastructure/transport",
    isProgrammaticHub: true,
    exampleSlugs: ["rail-bridge-attack-tracking", "road-network-damage-assessment"],
  },
  {
    id: "infra-water",
    parentDomain: "Infrastructure",
    name_en: "Water",
    name_uk: "Водопостачання",
    slugPrefix: "infrastructure/water",
    isProgrammaticHub: true,
    exampleSlugs: ["kakhovka-dam-breach-analysis", "water-treatment-attacks"],
  },
  {
    id: "infra-healthcare",
    parentDomain: "Infrastructure",
    name_en: "Healthcare",
    name_uk: "Охорона здоров'я",
    slugPrefix: "infrastructure/healthcare",
    isProgrammaticHub: true,
    exampleSlugs: ["hospital-attacks-documentation", "medical-supply-shortages"],
  },
  {
    id: "infra-education",
    parentDomain: "Infrastructure",
    name_en: "Education",
    name_uk: "Освіта",
    slugPrefix: "infrastructure/education",
    isProgrammaticHub: true,
    exampleSlugs: ["school-attacks-ukraine", "university-infrastructure-damage"],
  },
  {
    id: "infra-residential",
    parentDomain: "Infrastructure",
    name_en: "Residential",
    name_uk: "Житлова інфраструктура",
    slugPrefix: "infrastructure/residential",
    isProgrammaticHub: true,
    exampleSlugs: ["apartment-block-strikes-analysis", "civilian-housing-damage"],
  },
  {
    id: "infra-industrial",
    parentDomain: "Infrastructure",
    name_en: "Industrial",
    name_uk: "Промислова інфраструктура",
    slugPrefix: "infrastructure/industrial",
    isProgrammaticHub: true,
    exampleSlugs: ["steel-plant-attacks-mariupol", "refinery-strikes-tracking"],
  },
  {
    id: "infra-bridges",
    parentDomain: "Infrastructure",
    name_en: "Bridges",
    name_uk: "Мости",
    slugPrefix: "infrastructure/bridges",
    isProgrammaticHub: true,
    exampleSlugs: ["kerch-bridge-attack-analysis", "dnipro-bridge-damage-tracker"],
  },
  {
    id: "infra-ports",
    parentDomain: "Infrastructure",
    name_en: "Ports",
    name_uk: "Порти",
    slugPrefix: "infrastructure/ports",
    isProgrammaticHub: true,
    exampleSlugs: ["odesa-port-attacks", "grain-corridor-monitoring"],
  },

  // ── Cyber ──────────────────────────────────────────────────────────────────
  {
    id: "cyber-apt",
    parentDomain: "Cyber",
    name_en: "APT Groups",
    name_uk: "APT-групи",
    slugPrefix: "cyber/apt",
    isProgrammaticHub: true,
    exampleSlugs: ["sandworm-apt-profile", "fancy-bear-election-interference"],
  },
  {
    id: "cyber-ransomware",
    parentDomain: "Cyber",
    name_en: "Ransomware",
    name_uk: "Вимагацьке ПЗ",
    slugPrefix: "cyber/ransomware",
    isProgrammaticHub: true,
    exampleSlugs: ["lockbit-ransomware-tracking", "conti-group-analysis"],
  },
  {
    id: "cyber-ddos",
    parentDomain: "Cyber",
    name_en: "DDoS",
    name_uk: "DDoS-атаки",
    slugPrefix: "cyber/ddos",
    isProgrammaticHub: true,
    exampleSlugs: ["killnet-ddos-campaigns", "ukraine-government-ddos-attacks"],
  },
  {
    id: "cyber-phishing",
    parentDomain: "Cyber",
    name_en: "Phishing",
    name_uk: "Фішинг",
    slugPrefix: "cyber/phishing",
    isProgrammaticHub: true,
    exampleSlugs: ["spear-phishing-diplomat-targeting", "credential-harvesting-campaigns"],
  },
  {
    id: "cyber-ics-ot",
    parentDomain: "Cyber",
    name_en: "ICS / OT Security",
    name_uk: "Безпека ІКС / ОТ",
    slugPrefix: "cyber/ics-ot",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-power-grid-cyberattack-2015", "industroyer-malware-analysis"],
  },
  {
    id: "cyber-supply-chain",
    parentDomain: "Cyber",
    name_en: "Supply Chain Attacks",
    name_uk: "Атаки на ланцюги постачання",
    slugPrefix: "cyber/supply-chain",
    isProgrammaticHub: true,
    exampleSlugs: ["notpetya-supply-chain-origins", "software-update-hijacking"],
  },
  {
    id: "cyber-identity",
    parentDomain: "Cyber",
    name_en: "Identity Threats",
    name_uk: "Загрози ідентичності",
    slugPrefix: "cyber/identity",
    isProgrammaticHub: true,
    exampleSlugs: ["account-takeover-tracking", "credential-stuffing-campaigns"],
  },
  {
    id: "cyber-data-breach",
    parentDomain: "Cyber",
    name_en: "Data Breach",
    name_uk: "Витік даних",
    slugPrefix: "cyber/data-breach",
    isProgrammaticHub: true,
    exampleSlugs: ["ukrainian-government-data-leaks", "military-conscript-data-exposure"],
  },

  // ── Humanitarian ───────────────────────────────────────────────────────────
  {
    id: "humanitarian-displacement",
    parentDomain: "Humanitarian",
    name_en: "Displacement",
    name_uk: "Переміщення",
    slugPrefix: "humanitarian/displacement",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-idp-statistics-tracker", "refugee-flow-mapping"],
  },
  {
    id: "humanitarian-aid-corridors",
    parentDomain: "Humanitarian",
    name_en: "Aid Corridors",
    name_uk: "Гуманітарні коридори",
    slugPrefix: "humanitarian/aid-corridors",
    isProgrammaticHub: true,
    exampleSlugs: ["mariupol-evacuation-attempts", "zaporizhzhia-humanitarian-corridor"],
  },
  {
    id: "humanitarian-shelters",
    parentDomain: "Humanitarian",
    name_en: "Shelters",
    name_uk: "Притулки",
    slugPrefix: "humanitarian/shelters",
    isProgrammaticHub: true,
    exampleSlugs: ["metro-shelter-mapping-kharkiv", "collective-shelter-capacity"],
  },
  {
    id: "humanitarian-medical",
    parentDomain: "Humanitarian",
    name_en: "Medical",
    name_uk: "Медична допомога",
    slugPrefix: "humanitarian/medical",
    isProgrammaticHub: true,
    exampleSlugs: ["battlefield-trauma-care-gaps", "hospital-evacuation-tracking"],
  },
  {
    id: "humanitarian-food-security",
    parentDomain: "Humanitarian",
    name_en: "Food Security",
    name_uk: "Продовольча безпека",
    slugPrefix: "humanitarian/food-security",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-grain-export-disruption", "famine-risk-monitoring"],
  },
  {
    id: "humanitarian-wash",
    parentDomain: "Humanitarian",
    name_en: "WASH",
    name_uk: "Вода та санітарія (WASH)",
    slugPrefix: "humanitarian/wash",
    isProgrammaticHub: true,
    exampleSlugs: ["water-access-conflict-zones", "sanitation-collapse-mariupol"],
  },
  {
    id: "humanitarian-children",
    parentDomain: "Humanitarian",
    name_en: "Children",
    name_uk: "Діти",
    slugPrefix: "humanitarian/children",
    isProgrammaticHub: true,
    exampleSlugs: ["ukrainian-children-deportation-tracking", "child-casualties-documentation"],
  },
  {
    id: "humanitarian-disability",
    parentDomain: "Humanitarian",
    name_en: "Disability",
    name_uk: "Люди з інвалідністю",
    slugPrefix: "humanitarian/disability",
    isProgrammaticHub: true,
    exampleSlugs: ["disabled-persons-evacuation-challenges", "care-home-attacks"],
  },
  {
    id: "humanitarian-mine-action",
    parentDomain: "Humanitarian",
    name_en: "Mine Action",
    name_uk: "Протимінна діяльність",
    slugPrefix: "humanitarian/mine-action",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-mine-contamination-map", "cluster-munition-impact-sites"],
  },

  // ── Maritime ───────────────────────────────────────────────────────────────
  {
    id: "maritime-shadow-fleet",
    parentDomain: "Maritime",
    name_en: "Shadow Fleet",
    name_uk: "Тіньовий флот",
    slugPrefix: "maritime/shadow-fleet",
    isProgrammaticHub: true,
    exampleSlugs: ["russian-oil-shadow-fleet-tracker", "vessel-identity-changes"],
  },
  {
    id: "maritime-sanctions-evasion",
    parentDomain: "Maritime",
    name_en: "Sanctions Evasion",
    name_uk: "Обхід санкцій на морі",
    slugPrefix: "maritime/sanctions-evasion",
    isProgrammaticHub: true,
    exampleSlugs: ["ship-to-ship-transfers-tracking", "flag-hopping-analysis"],
  },
  {
    id: "maritime-port-ops",
    parentDomain: "Maritime",
    name_en: "Port Operations",
    name_uk: "Портові операції",
    slugPrefix: "maritime/port-ops",
    isProgrammaticHub: true,
    exampleSlugs: ["sevastopol-naval-base-monitoring", "novorossiysk-port-activity"],
  },
  {
    id: "maritime-cable-security",
    parentDomain: "Maritime",
    name_en: "Cable Security",
    name_uk: "Безпека підводних кабелів",
    slugPrefix: "maritime/cable-security",
    isProgrammaticHub: true,
    exampleSlugs: ["undersea-cable-sabotage-incidents", "baltic-sea-cable-threats"],
  },
  {
    id: "maritime-piracy",
    parentDomain: "Maritime",
    name_en: "Piracy",
    name_uk: "Піратство",
    slugPrefix: "maritime/piracy",
    isProgrammaticHub: true,
    exampleSlugs: ["red-sea-houthi-attacks", "gulf-of-guinea-piracy-tracker"],
  },
  {
    id: "maritime-naval-ops",
    parentDomain: "Maritime",
    name_en: "Naval Operations",
    name_uk: "Військово-морські операції",
    slugPrefix: "maritime/naval-ops",
    isProgrammaticHub: true,
    exampleSlugs: ["black-sea-naval-incidents", "russian-fleet-repositioning"],
  },
  {
    id: "maritime-fisheries",
    parentDomain: "Maritime",
    name_en: "Fisheries",
    name_uk: "Рибальство",
    slugPrefix: "maritime/fisheries",
    isProgrammaticHub: true,
    exampleSlugs: ["illegal-fishing-azov-sea", "north-korea-fishing-vessel-sanctions"],
  },

  // ── Aviation ───────────────────────────────────────────────────────────────
  {
    id: "aviation-civil",
    parentDomain: "Aviation",
    name_en: "Civil Aviation",
    name_uk: "Цивільна авіація",
    slugPrefix: "aviation/civil",
    isProgrammaticHub: true,
    exampleSlugs: ["airspace-closure-tracker", "airline-route-conflict-avoidance"],
  },
  {
    id: "aviation-military",
    parentDomain: "Aviation",
    name_en: "Military Aviation",
    name_uk: "Військова авіація",
    slugPrefix: "aviation/military",
    isProgrammaticHub: true,
    exampleSlugs: ["russian-aircraft-losses-tracker", "su-35-deployment-tracking"],
  },
  {
    id: "aviation-restricted-airspace",
    parentDomain: "Aviation",
    name_en: "Restricted Airspace",
    name_uk: "Закритий повітряний простір",
    slugPrefix: "aviation/restricted-airspace",
    isProgrammaticHub: true,
    exampleSlugs: ["ukraine-notam-monitoring", "no-fly-zone-documentation"],
  },
  {
    id: "aviation-drone-airspace",
    parentDomain: "Aviation",
    name_en: "Drone Airspace",
    name_uk: "Повітряний простір для БПЛА",
    slugPrefix: "aviation/drone-airspace",
    isProgrammaticHub: true,
    exampleSlugs: ["drone-incursion-monitoring", "uav-airspace-conflict-zones"],
  },
  {
    id: "aviation-diversions",
    parentDomain: "Aviation",
    name_en: "Diversions",
    name_uk: "Відхилення рейсів",
    slugPrefix: "aviation/diversions",
    isProgrammaticHub: true,
    exampleSlugs: ["ryanair-minsk-diversion-analysis", "forced-landing-incidents"],
  },
  {
    id: "aviation-refueling",
    parentDomain: "Aviation",
    name_en: "Refueling",
    name_uk: "Дозаправка",
    slugPrefix: "aviation/refueling",
    isProgrammaticHub: true,
    exampleSlugs: ["strategic-bomber-refueling-tracking", "tanker-aircraft-osint"],
  },

  // ── Politics & Diplomacy ───────────────────────────────────────────────────
  {
    id: "politics-treaties",
    parentDomain: "Politics & Diplomacy",
    name_en: "Treaties",
    name_uk: "Договори",
    slugPrefix: "politics/treaties",
    isProgrammaticHub: true,
    exampleSlugs: ["grain-deal-monitoring", "nato-membership-negotiations"],
  },
  {
    id: "politics-sanctions",
    parentDomain: "Politics & Diplomacy",
    name_en: "Sanctions",
    name_uk: "Санкції",
    slugPrefix: "politics/sanctions",
    isProgrammaticHub: true,
    exampleSlugs: ["eu-sanctions-package-tracker", "g7-russia-sanctions-timeline"],
  },
  {
    id: "politics-visits",
    parentDomain: "Politics & Diplomacy",
    name_en: "Official Visits",
    name_uk: "Офіційні візити",
    slugPrefix: "politics/visits",
    isProgrammaticHub: true,
    exampleSlugs: ["zelensky-foreign-visits-tracker", "western-leaders-kyiv-visits"],
  },
  {
    id: "politics-statements",
    parentDomain: "Politics & Diplomacy",
    name_en: "Statements",
    name_uk: "Заяви",
    slugPrefix: "politics/statements",
    isProgrammaticHub: true,
    exampleSlugs: ["kremlin-statement-analysis", "nato-secretary-general-statements"],
  },
  {
    id: "politics-recognition",
    parentDomain: "Politics & Diplomacy",
    name_en: "Recognition",
    name_uk: "Визнання",
    slugPrefix: "politics/recognition",
    isProgrammaticHub: true,
    exampleSlugs: ["crimea-annexation-recognition-tracker", "state-recognition-votes-un"],
  },
  {
    id: "politics-elections",
    parentDomain: "Politics & Diplomacy",
    name_en: "Elections",
    name_uk: "Вибори",
    slugPrefix: "politics/elections",
    isProgrammaticHub: true,
    exampleSlugs: ["russia-2024-election-monitoring", "georgia-election-crisis"],
  },
  {
    id: "politics-coups",
    parentDomain: "Politics & Diplomacy",
    name_en: "Coups",
    name_uk: "Перевороти",
    slugPrefix: "politics/coups",
    isProgrammaticHub: true,
    exampleSlugs: ["niger-coup-2023-analysis", "wagner-mutiny-documentation"],
  },

  // ── Economy & Sanctions ────────────────────────────────────────────────────
  {
    id: "economy-ofac",
    parentDomain: "Economy & Sanctions",
    name_en: "OFAC Sanctions",
    name_uk: "Санкції OFAC",
    slugPrefix: "economy/ofac",
    isProgrammaticHub: true,
    exampleSlugs: ["ofac-sdn-list-updates", "ofac-russia-designations"],
  },
  {
    id: "economy-eu-sanctions",
    parentDomain: "Economy & Sanctions",
    name_en: "EU Sanctions",
    name_uk: "Санкції ЄС",
    slugPrefix: "economy/eu-sanctions",
    isProgrammaticHub: true,
    exampleSlugs: ["eu-russia-sanctions-packages", "eu-asset-freeze-tracker"],
  },
  {
    id: "economy-uk-sanctions",
    parentDomain: "Economy & Sanctions",
    name_en: "UK Sanctions",
    name_uk: "Санкції Великої Британії",
    slugPrefix: "economy/uk-sanctions",
    isProgrammaticHub: true,
    exampleSlugs: ["uk-ofsi-designations", "uk-russia-sanctions-regime"],
  },
  {
    id: "economy-commodities",
    parentDomain: "Economy & Sanctions",
    name_en: "Commodities",
    name_uk: "Сировина та товари",
    slugPrefix: "economy/commodities",
    isProgrammaticHub: true,
    exampleSlugs: ["russian-oil-price-cap-monitoring", "wheat-market-conflict-impact"],
  },
  {
    id: "economy-energy-markets",
    parentDomain: "Economy & Sanctions",
    name_en: "Energy Markets",
    name_uk: "Енергетичні ринки",
    slugPrefix: "economy/energy-markets",
    isProgrammaticHub: true,
    exampleSlugs: ["lng-trade-flow-tracking", "europe-gas-storage-monitoring"],
  },
  {
    id: "economy-logistics-chains",
    parentDomain: "Economy & Sanctions",
    name_en: "Logistics Chains",
    name_uk: "Ланцюги постачання",
    slugPrefix: "economy/logistics-chains",
    isProgrammaticHub: true,
    exampleSlugs: ["dual-use-goods-smuggling", "sanctions-evasion-logistics-routes"],
  },

  // ── Information Environment ────────────────────────────────────────────────
  {
    id: "infoenv-disinfo-narratives",
    parentDomain: "Information Environment",
    name_en: "Disinformation Narratives",
    name_uk: "Дезінформаційні наративи",
    slugPrefix: "information/disinfo-narratives",
    isProgrammaticHub: true,
    exampleSlugs: ["kremlin-narrative-tracker", "false-flag-claims-analysis"],
  },
  {
    id: "infoenv-state-media",
    parentDomain: "Information Environment",
    name_en: "State Media",
    name_uk: "Державні медіа",
    slugPrefix: "information/state-media",
    isProgrammaticHub: true,
    exampleSlugs: ["rt-sputnik-messaging-analysis", "belarusian-state-media-monitoring"],
  },
  {
    id: "infoenv-bot-networks",
    parentDomain: "Information Environment",
    name_en: "Bot Networks",
    name_uk: "Мережі ботів",
    slugPrefix: "information/bot-networks",
    isProgrammaticHub: true,
    exampleSlugs: ["twitter-bot-network-detection", "telegram-amplification-analysis"],
  },
  {
    id: "infoenv-deepfakes",
    parentDomain: "Information Environment",
    name_en: "Deepfakes",
    name_uk: "Діпфейки",
    slugPrefix: "information/deepfakes",
    isProgrammaticHub: true,
    exampleSlugs: ["zelensky-deepfake-surrender-video", "deepfake-detection-tools-review"],
  },
  {
    id: "infoenv-suppression",
    parentDomain: "Information Environment",
    name_en: "Suppression",
    name_uk: "Придушення інформації",
    slugPrefix: "information/suppression",
    isProgrammaticHub: true,
    exampleSlugs: ["internet-shutdown-monitoring", "journalist-censorship-tracker"],
  },

  // ── Environment & Climate ──────────────────────────────────────────────────
  {
    id: "env-wildfires",
    parentDomain: "Environment & Climate",
    name_en: "Wildfires",
    name_uk: "Лісові пожежі",
    slugPrefix: "environment/wildfires",
    isProgrammaticHub: true,
    exampleSlugs: ["conflict-zone-wildfire-tracking", "chernobyl-forest-fire-satellite"],
  },
  {
    id: "env-floods",
    parentDomain: "Environment & Climate",
    name_en: "Floods",
    name_uk: "Повені",
    slugPrefix: "environment/floods",
    isProgrammaticHub: true,
    exampleSlugs: ["kakhovka-dam-flood-mapping", "kherson-inundation-satellite"],
  },
  {
    id: "env-drought",
    parentDomain: "Environment & Climate",
    name_en: "Drought",
    name_uk: "Посуха",
    slugPrefix: "environment/drought",
    isProgrammaticHub: true,
    exampleSlugs: ["sahel-drought-conflict-nexus", "ukraine-agricultural-drought-impact"],
  },
  {
    id: "env-pollution",
    parentDomain: "Environment & Climate",
    name_en: "Pollution",
    name_uk: "Забруднення",
    slugPrefix: "environment/pollution",
    isProgrammaticHub: true,
    exampleSlugs: ["mariupol-industrial-pollution", "azovstal-environmental-damage"],
  },
  {
    id: "env-nuclear",
    parentDomain: "Environment & Climate",
    name_en: "Nuclear",
    name_uk: "Ядерна небезпека",
    slugPrefix: "environment/nuclear",
    isProgrammaticHub: true,
    exampleSlugs: ["zaporizhzhia-nuclear-plant-monitoring", "radiation-monitoring-ukraine"],
  },
  {
    id: "env-industrial-accident",
    parentDomain: "Environment & Climate",
    name_en: "Industrial Accident",
    name_uk: "Промислові аварії",
    slugPrefix: "environment/industrial-accident",
    isProgrammaticHub: true,
    exampleSlugs: ["ammonia-leak-conflict-zones", "chemical-plant-strike-analysis"],
  },
];

/** Return all subcategories belonging to a top-level domain */
export function getSubcategoriesByDomain(domain: string): Subcategory[] {
  return SUBCATEGORIES.filter((s) => s.parentDomain === domain);
}

export const SUBCATEGORY_HUB_NOTE_EN =
  "Each subcategory is a programmatic hub URL. Phase 2 builds micro-category files.";

export const SUBCATEGORY_HUB_NOTE_UK =
  "Кожна підкатегорія — це програматичний хаб-URL. Фаза 2 будує файли мікрокатегорій.";
