/**
 * Alert System Config — multi-channel alert delivery with rule engine.
 *
 * Users define rules (keyword, entity, AOI, threshold, AI suggestion).
 * Alerts are delivered over configurable channels with deduplification
 * and quiet-hour support.
 *
 * Система алертів: правила + AI-пропозиції + багатоканальна доставка.
 */

'use server';

// ── Channels ──────────────────────────────────────────────────────────────────

export type AlertChannel = 'email' | 'telegram' | 'slack' | 'discord' | 'webhook' | 'sms';

export const ALERT_CHANNELS: AlertChannel[] = [
  'email', 'telegram', 'slack', 'discord', 'webhook', 'sms',
];

// ── Rule types ────────────────────────────────────────────────────────────────

export type AlertRuleType =
  | 'keyword'
  | 'entity'
  | 'aoi'
  | 'threshold'
  | 'ai-suggestion';

export const ALERT_RULE_TYPES: AlertRuleType[] = [
  'keyword', 'entity', 'aoi', 'threshold', 'ai-suggestion',
];

// ── Rule shape ────────────────────────────────────────────────────────────────

export interface AlertRule {
  id: string;
  userId: string;
  type: AlertRuleType;
  /** Rule-specific parameters (keywords[], entityId, aoiId, metric+threshold) */
  params: Record<string, unknown>;
  channels: AlertChannel[];
  /** Whether the rule is active — Чи активне правило */
  enabled: boolean;
  /** Minimum danger score to trigger — Мін. danger score для тригера */
  minDangerScore: number;
  /** Minimum confidence score to trigger — Мін. confidence для тригера */
  minConfidence: number;
  /** Deduplification window in minutes — Вікно дедублікації (хв) */
  dedupWindowMinutes: number;
  /** Quiet hours UTC (e.g. [22, 6]) — Тихий час UTC */
  quietHoursUtc: [number, number] | null;
}

// ── Channel configs ───────────────────────────────────────────────────────────

export interface ChannelConfig {
  channel: AlertChannel;
  /** Max alerts per user per hour — Макс. алертів на користувача за годину */
  rateLimitPerHour: number;
  /** Auth/credential type — Тип авторизації */
  authType: string;
  /** Whether rich HTML/markdown is supported — Чи підтримується форматування */
  richFormat: boolean;
  /** Required tier — Необхідний tier */
  requiredTier: string;
}

export const CHANNEL_CONFIGS: Record<AlertChannel, ChannelConfig> = {
  email:    { channel: 'email',    rateLimitPerHour: 20,  authType: 'smtp',          richFormat: true,  requiredTier: 'free'       },
  telegram: { channel: 'telegram', rateLimitPerHour: 30,  authType: 'bot-token',     richFormat: true,  requiredTier: 'free'       },
  slack:    { channel: 'slack',    rateLimitPerHour: 60,  authType: 'webhook-url',   richFormat: true,  requiredTier: 'observer'   },
  discord:  { channel: 'discord',  rateLimitPerHour: 60,  authType: 'webhook-url',   richFormat: true,  requiredTier: 'observer'   },
  webhook:  { channel: 'webhook',  rateLimitPerHour: 120, authType: 'hmac-secret',   richFormat: false, requiredTier: 'pro'        },
  sms:      { channel: 'sms',      rateLimitPerHour: 5,   authType: 'twilio-api-key', richFormat: false, requiredTier: 'enterprise' },
};

// ── System config ─────────────────────────────────────────────────────────────

export interface AlertSystemConfig {
  channels: AlertChannel[];
  ruleTypes: AlertRuleType[];
  channelConfigs: Record<AlertChannel, ChannelConfig>;
  /** Max rules per user — Макс. правил на користувача */
  maxRulesPerUser: number;
  /** Max channels per rule — Макс. каналів на правило */
  maxChannelsPerRule: number;
  /** Global deduplification TTL in minutes — Глобальний TTL дедублікації (хв) */
  globalDedupTtlMinutes: number;
}

export const ALERT_SYSTEM_CONFIG: AlertSystemConfig = {
  channels: ALERT_CHANNELS,
  ruleTypes: ALERT_RULE_TYPES,
  channelConfigs: CHANNEL_CONFIGS,
  maxRulesPerUser: 50,
  maxChannelsPerRule: 3,
  globalDedupTtlMinutes: 60,
};

// ── Notes ─────────────────────────────────────────────────────────────────────

export const ALERT_NOTE_EN =
  'AI-suggestion rules are generated by the AI copilot based on analyst activity patterns. ' +
  'Users can promote suggestions to permanent rules with one click.';

export const ALERT_NOTE_UK =
  'Правила типу ai-suggestion генерує AI-копілот на основі паттернів активності аналітика. ' +
  'Користувач може перетворити пропозицію на постійне правило одним кліком.';
