/**
 * Backlink hygiene — disavow file generation + audit schedule.
 * Keeps the backlink profile clean from spammy / toxic domains.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export interface DisavowEntry {
  domain: string;
  /** Short human-readable reason for disavowal */
  reason: string;
  /** ISO 8601 date when added */
  addedAt: string;
  /** Who added this entry (username or "auto") */
  addedBy: string;
}

export interface BacklinkAuditEntry {
  domain: string;
  url: string;
  anchor: string;
  /** Domain Rating (Ahrefs scale 0–100) */
  dr: number;
  followType: "follow" | "nofollow";
  /** ISO 8601 date of last check */
  lastChecked: string;
  status: "active" | "lost" | "disavowed";
}

// ── Disavow file constants ────────────────────────────────────────────────────

export const DISAVOW_FILE_HEADER = `# Aegis Lens — Google Disavow File
# Generated by backlink-hygiene.ts
# Format: https://support.google.com/webmasters/answer/2648487
# Submit at: https://search.google.com/search-console/disavow-links
#
# IMPORTANT: Only disavow domains that are clearly toxic/spammy.
# Disavowing legitimate (even low-DR) links can harm rankings.
# Review with SEO lead before each submission.
#
# Last updated: AUTO_TIMESTAMP
`;

// ── Functions ─────────────────────────────────────────────────────────────────

/**
 * Builds a Google-format disavow.txt from DisavowEntry array.
 * Output should be saved to /disavow.txt and uploaded to GSC.
 */
export function buildDisavowFile(entries: DisavowEntry[]): string {
  const timestamp = new Date().toISOString().split("T")[0];
  const header = DISAVOW_FILE_HEADER.replace("AUTO_TIMESTAMP", timestamp);

  const lines = entries.map((e) => {
    const comment = `# ${e.reason} | added: ${e.addedAt} | by: ${e.addedBy}`;
    return `${comment}\ndomain:${e.domain}`;
  });

  return [header, ...lines].join("\n\n");
}

/**
 * Filters audit entries by status.
 */
export function filterAuditByStatus(
  entries: BacklinkAuditEntry[],
  status: BacklinkAuditEntry["status"],
): BacklinkAuditEntry[] {
  return entries.filter((e) => e.status === status);
}

/**
 * Returns audit entries below a DR threshold (potential toxic links).
 */
export function getLowDrLinks(
  entries: BacklinkAuditEntry[],
  drThreshold = 10,
): BacklinkAuditEntry[] {
  return entries.filter((e) => e.dr < drThreshold && e.status === "active");
}

// ── Audit schedule ────────────────────────────────────────────────────────────

export const BACKLINK_AUDIT_SCHEDULE: {
  quarterly: boolean;
  toolRecommendations: string[];
  auditChecklist_en: string[];
} = {
  quarterly: true,
  toolRecommendations: [
    "Ahrefs Site Explorer → Backlinks → New/Lost tabs",
    "Semrush Backlink Audit tool (toxicity score filter)",
    "Google Search Console → Links report (manual review)",
    "Majestic (Trust Flow / Citation Flow ratio check)",
  ],
  auditChecklist_en: [
    "Export all new referring domains acquired since last audit",
    "Filter by DR < 10 — flag for manual review",
    "Check anchor text distribution — over-optimised exact-match anchors are a red flag",
    "Review lost backlinks — identify high-DR links lost and attempt recovery (outreach)",
    "Cross-reference new domains against spam databases (Semrush toxicity score > 60 = review)",
    "Check for sudden spike in links from a single country (link scheme signal)",
    "Verify no money-page anchors from irrelevant domains",
    "Review nofollow → dofollow ratio — should be >30% follow for healthy profile",
    "Update disavow file with newly identified toxic domains",
    "Submit updated disavow file to Google Search Console if changes were made",
  ],
};

// ── Sample disavow entries (starter — populate as needed) ─────────────────────

export const INITIAL_DISAVOW_ENTRIES: DisavowEntry[] = [
  // Add toxic domains as they are discovered during quarterly audits.
  // Example structure (uncomment and populate):
  // {
  //   domain: "toxic-link-farm.com",
  //   reason: "Obvious link farm — DR 2, casino content",
  //   addedAt: "2026-Q2",
  //   addedBy: "seo-lead",
  // },
];
