/**
 * Press relationship registry — top outlets for digital PR and backlink acquisition.
 * Bellingcat playbook: earn links via open data + methodology + collabs; never buy.
 */

export interface PressOutlet {
  name: string;
  region: "global" | "ukraine" | "eu" | "us" | "uk" | "pl" | "de";
  type: "newspaper" | "wire" | "broadcast" | "digital" | "newsletter";
  domainRating?: number;
  languages: string[];
  contactEmail?: string;
  verifiedPress: boolean;
  /** Primary domain used for email-domain verification */
  domain?: string;
}

export const PRESS_RELATIONSHIPS: PressOutlet[] = [
  // ── Global ────────────────────────────────────────────────────────────────
  {
    name: "Financial Times",
    region: "global",
    type: "newspaper",
    domainRating: 94,
    languages: ["en"],
    verifiedPress: true,
    domain: "ft.com",
  },
  {
    name: "The New York Times",
    region: "us",
    type: "newspaper",
    domainRating: 95,
    languages: ["en"],
    verifiedPress: true,
    domain: "nytimes.com",
  },
  {
    name: "Reuters",
    region: "global",
    type: "wire",
    domainRating: 93,
    languages: ["en", "de", "fr", "es", "ar", "uk"],
    verifiedPress: true,
    domain: "reuters.com",
  },
  {
    name: "Associated Press",
    region: "global",
    type: "wire",
    domainRating: 92,
    languages: ["en"],
    verifiedPress: true,
    domain: "apnews.com",
  },
  {
    name: "BBC News",
    region: "uk",
    type: "broadcast",
    domainRating: 95,
    languages: ["en", "uk", "ru"],
    verifiedPress: true,
    domain: "bbc.com",
  },
  {
    name: "The Guardian",
    region: "uk",
    type: "newspaper",
    domainRating: 93,
    languages: ["en"],
    verifiedPress: true,
    domain: "theguardian.com",
  },
  {
    name: "The Wall Street Journal",
    region: "us",
    type: "newspaper",
    domainRating: 93,
    languages: ["en"],
    verifiedPress: true,
    domain: "wsj.com",
  },
  {
    name: "Bloomberg",
    region: "global",
    type: "digital",
    domainRating: 92,
    languages: ["en"],
    verifiedPress: true,
    domain: "bloomberg.com",
  },
  {
    name: "The Economist",
    region: "global",
    type: "newspaper",
    domainRating: 91,
    languages: ["en"],
    verifiedPress: true,
    domain: "economist.com",
  },
  {
    name: "Foreign Policy",
    region: "us",
    type: "digital",
    domainRating: 85,
    languages: ["en"],
    verifiedPress: true,
    domain: "foreignpolicy.com",
  },
  {
    name: "Foreign Affairs",
    region: "us",
    type: "digital",
    domainRating: 84,
    languages: ["en"],
    verifiedPress: true,
    domain: "foreignaffairs.com",
  },
  {
    name: "The Atlantic",
    region: "us",
    type: "digital",
    domainRating: 88,
    languages: ["en"],
    verifiedPress: true,
    domain: "theatlantic.com",
  },
  {
    name: "Wired",
    region: "us",
    type: "digital",
    domainRating: 87,
    languages: ["en"],
    verifiedPress: true,
    domain: "wired.com",
  },
  // ── Ukraine ───────────────────────────────────────────────────────────────
  {
    name: "Kyiv Independent",
    region: "ukraine",
    type: "digital",
    domainRating: 72,
    languages: ["en"],
    verifiedPress: true,
    domain: "kyivindependent.com",
  },
  {
    name: "Ukrainska Pravda",
    region: "ukraine",
    type: "digital",
    domainRating: 70,
    languages: ["uk", "ru"],
    verifiedPress: true,
    domain: "pravda.com.ua",
  },
  {
    name: "Ukrinform",
    region: "ukraine",
    type: "wire",
    domainRating: 65,
    languages: ["uk", "en", "de", "fr", "es"],
    verifiedPress: true,
    domain: "ukrinform.ua",
  },
  {
    name: "Hromadske",
    region: "ukraine",
    type: "broadcast",
    domainRating: 62,
    languages: ["uk", "en"],
    verifiedPress: true,
    domain: "hromadske.ua",
  },
  {
    name: "Ukrainian Week",
    region: "ukraine",
    type: "digital",
    domainRating: 50,
    languages: ["uk", "en"],
    verifiedPress: true,
    domain: "ukrainianweek.com",
  },
  // ── EU ────────────────────────────────────────────────────────────────────
  {
    name: "Deutsche Welle",
    region: "eu",
    type: "broadcast",
    domainRating: 88,
    languages: ["de", "en", "uk", "ru", "fr"],
    verifiedPress: true,
    domain: "dw.com",
  },
  {
    name: "Le Monde",
    region: "eu",
    type: "newspaper",
    domainRating: 88,
    languages: ["fr"],
    verifiedPress: true,
    domain: "lemonde.fr",
  },
  {
    name: "Frankfurter Allgemeine Zeitung",
    region: "de",
    type: "newspaper",
    domainRating: 85,
    languages: ["de"],
    verifiedPress: true,
    domain: "faz.net",
  },
  {
    name: "Politico EU",
    region: "eu",
    type: "digital",
    domainRating: 86,
    languages: ["en"],
    verifiedPress: true,
    domain: "politico.eu",
  },
  {
    name: "Der Spiegel",
    region: "de",
    type: "digital",
    domainRating: 87,
    languages: ["de", "en"],
    verifiedPress: true,
    domain: "spiegel.de",
  },
  {
    name: "Süddeutsche Zeitung",
    region: "de",
    type: "newspaper",
    domainRating: 84,
    languages: ["de"],
    verifiedPress: true,
    domain: "sueddeutsche.de",
  },
  {
    name: "Euronews",
    region: "eu",
    type: "broadcast",
    domainRating: 80,
    languages: ["en", "fr", "de", "uk"],
    verifiedPress: true,
    domain: "euronews.com",
  },
  {
    name: "EUobserver",
    region: "eu",
    type: "digital",
    domainRating: 72,
    languages: ["en"],
    verifiedPress: true,
    domain: "euobserver.com",
  },
  // ── Poland ────────────────────────────────────────────────────────────────
  {
    name: "Gazeta Wyborcza",
    region: "pl",
    type: "newspaper",
    domainRating: 75,
    languages: ["pl"],
    verifiedPress: true,
    domain: "wyborcza.pl",
  },
  {
    name: "OKO.press",
    region: "pl",
    type: "digital",
    domainRating: 60,
    languages: ["pl"],
    verifiedPress: true,
    domain: "oko.press",
  },
  {
    name: "TVN24",
    region: "pl",
    type: "broadcast",
    domainRating: 70,
    languages: ["pl"],
    verifiedPress: true,
    domain: "tvn24.pl",
  },
  {
    name: "Rzeczpospolita",
    region: "pl",
    type: "newspaper",
    domainRating: 72,
    languages: ["pl"],
    verifiedPress: true,
    domain: "rp.pl",
  },
  // ── Baltic ────────────────────────────────────────────────────────────────
  {
    name: "Delfi",
    region: "eu",
    type: "digital",
    domainRating: 62,
    languages: ["lt", "lv", "et", "en"],
    verifiedPress: true,
    domain: "delfi.lt",
  },
  {
    name: "LRT (Lithuanian National Radio and Television)",
    region: "eu",
    type: "broadcast",
    domainRating: 60,
    languages: ["lt", "en"],
    verifiedPress: true,
    domain: "lrt.lt",
  },
  {
    name: "Postimees",
    region: "eu",
    type: "newspaper",
    domainRating: 58,
    languages: ["et", "ru"],
    verifiedPress: true,
    domain: "postimees.ee",
  },
  {
    name: "LSM (Latvijas Sabiedriskie Mediji)",
    region: "eu",
    type: "broadcast",
    domainRating: 55,
    languages: ["lv", "en", "ru"],
    verifiedPress: true,
    domain: "lsm.lv",
  },
  // ── OSINT / Security ──────────────────────────────────────────────────────
  {
    name: "Bellingcat",
    region: "global",
    type: "digital",
    domainRating: 78,
    languages: ["en"],
    verifiedPress: true,
    domain: "bellingcat.com",
  },
  {
    name: "IntelligenceOnline",
    region: "global",
    type: "newsletter",
    domainRating: 55,
    languages: ["en", "fr"],
    verifiedPress: true,
    domain: "intelligenceonline.com",
  },
  {
    name: "ACLED (blog)",
    region: "global",
    type: "digital",
    domainRating: 72,
    languages: ["en"],
    verifiedPress: false,
    domain: "acleddata.com",
  },
  {
    name: "International Crisis Group",
    region: "global",
    type: "digital",
    domainRating: 80,
    languages: ["en", "fr"],
    verifiedPress: false,
    domain: "crisisgroup.org",
  },
  {
    name: "Institute for the Study of War (ISW)",
    region: "us",
    type: "digital",
    domainRating: 74,
    languages: ["en"],
    verifiedPress: false,
    domain: "understandingwar.org",
  },
  {
    name: "War on the Rocks",
    region: "us",
    type: "digital",
    domainRating: 70,
    languages: ["en"],
    verifiedPress: true,
    domain: "warontherocks.com",
  },
  {
    name: "Just Security",
    region: "us",
    type: "digital",
    domainRating: 68,
    languages: ["en"],
    verifiedPress: true,
    domain: "justsecurity.org",
  },
  // ── UN / Humanitarian ────────────────────────────────────────────────────
  {
    name: "OCHA ReliefWeb",
    region: "global",
    type: "digital",
    domainRating: 82,
    languages: ["en", "fr"],
    verifiedPress: false,
    domain: "reliefweb.int",
  },
  {
    name: "UNHCR",
    region: "global",
    type: "digital",
    domainRating: 85,
    languages: ["en", "fr", "uk"],
    verifiedPress: false,
    domain: "unhcr.org",
  },
  {
    name: "ICRC",
    region: "global",
    type: "digital",
    domainRating: 84,
    languages: ["en", "fr", "de", "uk"],
    verifiedPress: false,
    domain: "icrc.org",
  },
  {
    name: "MSF / Médecins Sans Frontières",
    region: "global",
    type: "digital",
    domainRating: 82,
    languages: ["en", "fr"],
    verifiedPress: false,
    domain: "msf.org",
  },
  {
    name: "Human Rights Watch",
    region: "global",
    type: "digital",
    domainRating: 86,
    languages: ["en"],
    verifiedPress: false,
    domain: "hrw.org",
  },
  {
    name: "Amnesty International",
    region: "global",
    type: "digital",
    domainRating: 85,
    languages: ["en", "fr", "de"],
    verifiedPress: false,
    domain: "amnesty.org",
  },
  // ── UK Outlets ────────────────────────────────────────────────────────────
  {
    name: "The Times (London)",
    region: "uk",
    type: "newspaper",
    domainRating: 90,
    languages: ["en"],
    verifiedPress: true,
    domain: "thetimes.co.uk",
  },
  {
    name: "The Telegraph",
    region: "uk",
    type: "newspaper",
    domainRating: 89,
    languages: ["en"],
    verifiedPress: true,
    domain: "telegraph.co.uk",
  },
  {
    name: "Sky News",
    region: "uk",
    type: "broadcast",
    domainRating: 88,
    languages: ["en"],
    verifiedPress: true,
    domain: "news.sky.com",
  },
  {
    name: "The Independent",
    region: "uk",
    type: "digital",
    domainRating: 83,
    languages: ["en"],
    verifiedPress: true,
    domain: "independent.co.uk",
  },
  {
    name: "openDemocracy",
    region: "uk",
    type: "digital",
    domainRating: 73,
    languages: ["en"],
    verifiedPress: true,
    domain: "opendemocracy.net",
  },
];

/**
 * Returns all outlets for a given region.
 */
export function getOutletsByRegion(region: PressOutlet["region"]): PressOutlet[] {
  return PRESS_RELATIONSHIPS.filter((o) => o.region === region);
}

/**
 * Returns outlets marked as verified press (suitable for press-tier discount).
 */
export function getVerifiedPressOutlets(): PressOutlet[] {
  return PRESS_RELATIONSHIPS.filter((o) => o.verifiedPress);
}

/**
 * Returns outlets supporting a given language.
 */
export function getOutletsByLanguage(lang: string): PressOutlet[] {
  return PRESS_RELATIONSHIPS.filter((o) => o.languages.includes(lang));
}
