/**
 * axe-core CI integration configuration for Aegis Lens.
 *
 * Failing criterion:   any violation at impact 'serious' or 'critical'
 * Test runner:         Node.js script generated by buildAxeScript()
 * Triggered by:        GitHub Actions on every PR targeting main
 *
 * Reference: https://github.com/dequelabs/axe-core
 */

export interface AxeCiConfig {
  /** axe-core rule IDs to explicitly enable (on top of the default set). */
  enabledRules: string[];
  /** axe-core rule IDs to disable for this project (e.g. known false positives). */
  disabledRules: string[];
  /** Minimum impact level that causes a CI failure. */
  failOnImpact: "serious" | "critical";
  /** Pages (relative paths) to test in CI. */
  pagesToTest: string[];
  /** Base URL for axe test runs (typically the preview deployment URL). */
  baseUrl: string;
  /** Browser viewport for testing. */
  viewport: { width: number; height: number };
}

export const AXE_CI_CONFIG: AxeCiConfig = {
  enabledRules: [
    "color-contrast",
    "color-contrast-enhanced",
    "focus-visible",
    "keyboard-focusable-scrollable",
    "target-size",
    "aria-allowed-attr",
    "aria-required-attr",
    "aria-valid-attr",
    "aria-valid-attr-value",
    "label",
    "link-name",
    "button-name",
    "image-alt",
    "input-image-alt",
    "frame-title",
    "html-lang-valid",
    "skip-link",
    "landmark-one-main",
    "page-has-heading-one",
    "duplicate-id-active",
  ],
  disabledRules: [
    // Third-party embeds (Mapbox / Cesium) inject iframes without titles —
    // excluded at selector level rather than rule level where possible.
    // "frame-title" kept enabled; excluded via AXE_EXCLUDED_SELECTORS instead.
  ],
  failOnImpact: "serious",
  pagesToTest: [
    "/",
    "/for/analyst",
    "/for/journalist",
    "/for/government",
    "/compare",
    "/signup",
    "/login",
    "/map",
    "/pricing",
    "/about",
  ],
  baseUrl: process.env.NEXT_PUBLIC_PREVIEW_URL ?? "http://localhost:3000",
  viewport: { width: 1280, height: 800 },
};

/**
 * CSS selectors to exclude from axe checks.
 * These are typically third-party embeds or known non-fixable elements.
 */
export const AXE_EXCLUDED_SELECTORS: string[] = [
  // Mapbox GL iframe injected at runtime — vendor responsibility
  ".mapboxgl-canvas",
  // Cesium / Resium canvas — vendor responsibility
  ".cesium-widget canvas",
  // Cookie consent widget (third-party)
  "#cookieyes-root",
  // Intercom chat widget (third-party)
  "#intercom-container",
];

/**
 * Returns a Node.js script string that runs axe-core against all configured
 * pages using Playwright. Write this to a file (e.g. scripts/axe-ci.mjs)
 * and execute via `node scripts/axe-ci.mjs` in CI.
 *
 * Requires: @axe-core/playwright + @playwright/test installed as devDependencies.
 */
export function buildAxeScript(): string {
  const config = AXE_CI_CONFIG;
  const excluded = AXE_EXCLUDED_SELECTORS.map((s) => `"${s}"`).join(",\n      ");

  return `/**
 * axe-core CI accessibility test — auto-generated by axe-ci-config.ts
 * Run: node scripts/axe-ci.mjs
 */
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";

const BASE_URL = process.env.NEXT_PUBLIC_PREVIEW_URL ?? "${config.baseUrl}";
const PAGES = ${JSON.stringify(config.pagesToTest, null, 2)};
const FAIL_ON_IMPACT = "${config.failOnImpact}";
const IMPACT_ORDER = ["minor", "moderate", "serious", "critical"];
const EXCLUDED = [
  ${excluded}
];

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: ${config.viewport.width}, height: ${config.viewport.height} },
  });

  let totalViolations = 0;

  for (const page of PAGES) {
    const pageObj = await context.newPage();
    await pageObj.goto(BASE_URL + page, { waitUntil: "networkidle" });

    const builder = new AxeBuilder({ page: pageObj })
      .withRules(${JSON.stringify(config.enabledRules)})
      .exclude(EXCLUDED);

    const results = await builder.analyze();

    const failing = results.violations.filter((v) => {
      const idx = IMPACT_ORDER.indexOf(v.impact ?? "minor");
      return idx >= IMPACT_ORDER.indexOf(FAIL_ON_IMPACT);
    });

    if (failing.length > 0) {
      console.error("\\n[axe] FAIL:", page);
      failing.forEach((v) => {
        console.error(\`  [\${v.impact}] \${v.id}: \${v.description}\`);
        v.nodes.forEach((n) => console.error("    ->", n.html));
      });
      totalViolations += failing.length;
    } else {
      console.log("[axe] PASS:", page);
    }

    await pageObj.close();
  }

  await browser.close();

  if (totalViolations > 0) {
    console.error(\`\\n[axe] \${totalViolations} violation(s) at \${FAIL_ON_IMPACT}+ level. Build failed.\`);
    process.exit(1);
  }

  console.log("\\n[axe] All pages passed accessibility checks.");
})();
`.trim();
}
