/**
 * Component Library Registry
 *
 * Single source of truth for the Aegis Lens design system:
 * which shadcn/ui components are used, which Radix primitives
 * they depend on, and where each component lives in the monorepo.
 *
 * Sprint 2.73 — Design foundations
 */

// ── shadcn/ui components in use ──────────────────────────────────────────────

/**
 * Canonical list of shadcn/ui components installed in apps/web.
 * Each entry corresponds to a file generated by `npx shadcn-ui add <name>`.
 *
 * To add a new component:
 *   npx shadcn-ui add <name>
 *   Then append the name here and register it in ComponentRegistry below.
 */
export const SHADCN_COMPONENTS = [
  "button",
  "card",
  "dialog",
  "dropdown-menu",
  "input",
  "select",
  "sheet",
  "tabs",
  "tooltip",
  "badge",
  "avatar",
  "skeleton",
  "progress",
  "separator",
  "scroll-area",
  "popover",
  "command",
  "label",
  "switch",
  "slider",
  "checkbox",
  "radio-group",
  "toggle",
  "toggle-group",
  "alert",
  "alert-dialog",
  "toast",
  "sonner",
  "table",
] as const;

export type ShadcnComponent = (typeof SHADCN_COMPONENTS)[number];

// ── Radix UI primitives used (direct or via shadcn) ──────────────────────────

/**
 * Every @radix-ui package that apps/web depends on, either directly
 * or transitively through shadcn/ui. Kept explicit so dependency
 * audits can verify nothing unexpected is pulled in.
 */
export const RADIX_PRIMITIVES_USED: string[] = [
  "@radix-ui/react-accordion",
  "@radix-ui/react-alert-dialog",
  "@radix-ui/react-aspect-ratio",
  "@radix-ui/react-avatar",
  "@radix-ui/react-checkbox",
  "@radix-ui/react-collapsible",
  "@radix-ui/react-context-menu",
  "@radix-ui/react-dialog",
  "@radix-ui/react-dropdown-menu",
  "@radix-ui/react-hover-card",
  "@radix-ui/react-label",
  "@radix-ui/react-menubar",
  "@radix-ui/react-navigation-menu",
  "@radix-ui/react-popover",
  "@radix-ui/react-progress",
  "@radix-ui/react-radio-group",
  "@radix-ui/react-scroll-area",
  "@radix-ui/react-select",
  "@radix-ui/react-separator",
  "@radix-ui/react-slider",
  "@radix-ui/react-slot",
  "@radix-ui/react-switch",
  "@radix-ui/react-tabs",
  "@radix-ui/react-toast",
  "@radix-ui/react-toggle",
  "@radix-ui/react-toggle-group",
  "@radix-ui/react-tooltip",
];

// ── Component registry ────────────────────────────────────────────────────────

/**
 * Maps every UI component to its source file relative to apps/web/src.
 * Custom components live in components/ui/; shadcn generated components
 * also live there. Domain-specific composites are in components/<domain>/.
 */
export const ComponentRegistry: Record<string, string> = {
  // ── shadcn/ui primitives ──────────────────────────────────────────────────
  Button: "components/ui/button.tsx",
  Card: "components/ui/card.tsx",
  CardHeader: "components/ui/card.tsx",
  CardContent: "components/ui/card.tsx",
  CardFooter: "components/ui/card.tsx",
  Dialog: "components/ui/dialog.tsx",
  DialogContent: "components/ui/dialog.tsx",
  DialogHeader: "components/ui/dialog.tsx",
  DialogTitle: "components/ui/dialog.tsx",
  DialogDescription: "components/ui/dialog.tsx",
  DialogFooter: "components/ui/dialog.tsx",
  DropdownMenu: "components/ui/dropdown-menu.tsx",
  DropdownMenuTrigger: "components/ui/dropdown-menu.tsx",
  DropdownMenuContent: "components/ui/dropdown-menu.tsx",
  DropdownMenuItem: "components/ui/dropdown-menu.tsx",
  DropdownMenuSeparator: "components/ui/dropdown-menu.tsx",
  DropdownMenuLabel: "components/ui/dropdown-menu.tsx",
  Input: "components/ui/input.tsx",
  Select: "components/ui/select.tsx",
  SelectTrigger: "components/ui/select.tsx",
  SelectContent: "components/ui/select.tsx",
  SelectItem: "components/ui/select.tsx",
  SelectValue: "components/ui/select.tsx",
  Sheet: "components/ui/sheet.tsx",
  SheetContent: "components/ui/sheet.tsx",
  SheetHeader: "components/ui/sheet.tsx",
  SheetTitle: "components/ui/sheet.tsx",
  SheetDescription: "components/ui/sheet.tsx",
  Tabs: "components/ui/tabs.tsx",
  TabsList: "components/ui/tabs.tsx",
  TabsTrigger: "components/ui/tabs.tsx",
  TabsContent: "components/ui/tabs.tsx",
  Tooltip: "components/ui/tooltip.tsx",
  TooltipTrigger: "components/ui/tooltip.tsx",
  TooltipContent: "components/ui/tooltip.tsx",
  TooltipProvider: "components/ui/tooltip.tsx",
  Badge: "components/ui/badge.tsx",
  Avatar: "components/ui/avatar.tsx",
  AvatarImage: "components/ui/avatar.tsx",
  AvatarFallback: "components/ui/avatar.tsx",
  Skeleton: "components/ui/skeleton.tsx",
  Progress: "components/ui/progress.tsx",
  Separator: "components/ui/separator.tsx",
  ScrollArea: "components/ui/scroll-area.tsx",
  Popover: "components/ui/popover.tsx",
  PopoverTrigger: "components/ui/popover.tsx",
  PopoverContent: "components/ui/popover.tsx",
  Command: "components/ui/command.tsx",
  CommandInput: "components/ui/command.tsx",
  CommandList: "components/ui/command.tsx",
  CommandGroup: "components/ui/command.tsx",
  CommandItem: "components/ui/command.tsx",
  CommandShortcut: "components/ui/command.tsx",
  CommandSeparator: "components/ui/command.tsx",
  CommandEmpty: "components/ui/command.tsx",
  Label: "components/ui/label.tsx",
  Switch: "components/ui/switch.tsx",
  Slider: "components/ui/slider.tsx",
  Checkbox: "components/ui/checkbox.tsx",
  RadioGroup: "components/ui/radio-group.tsx",
  RadioGroupItem: "components/ui/radio-group.tsx",
  Toggle: "components/ui/toggle.tsx",
  ToggleGroup: "components/ui/toggle-group.tsx",
  Alert: "components/ui/alert.tsx",
  AlertTitle: "components/ui/alert.tsx",
  AlertDescription: "components/ui/alert.tsx",
  AlertDialog: "components/ui/alert-dialog.tsx",
  AlertDialogContent: "components/ui/alert-dialog.tsx",
  AlertDialogAction: "components/ui/alert-dialog.tsx",
  AlertDialogCancel: "components/ui/alert-dialog.tsx",
  Toast: "components/ui/toast.tsx",
  ToastProvider: "components/ui/toast.tsx",
  Table: "components/ui/table.tsx",
  TableHeader: "components/ui/table.tsx",
  TableBody: "components/ui/table.tsx",
  TableRow: "components/ui/table.tsx",
  TableHead: "components/ui/table.tsx",
  TableCell: "components/ui/table.tsx",
  TableFooter: "components/ui/table.tsx",

  // ── Intelligence-domain custom components ─────────────────────────────────
  IncidentCard: "components/incidents/IncidentCard.tsx",
  ConfidenceChip: "components/chips/ConfidenceChip.tsx",
  DangerChip: "components/chips/DangerChip.tsx",
  VerificationChip: "components/chips/VerificationChip.tsx",
  SeverityBar: "components/chips/SeverityBar.tsx",
  SourcePill: "components/sources/SourcePill.tsx",
  DataTable: "components/data/DataTable.tsx",
  CommandPalette: "components/command/CommandPalette.tsx",
  CommandPaletteProvider: "components/command/CommandPaletteProvider.tsx",
  MapTimelineBar: "components/map/MapTimelineBar.tsx",
  LayerToggles: "components/map/LayerToggles.tsx",
  FilterBar: "components/map/FilterBar.tsx",
  CopilotPanel: "components/copilot/CopilotPanel.tsx",
  Modal: "components/ui/Modal.tsx",
  Drawer: "components/ui/Drawer.tsx",
  EmptyState: "components/ui/EmptyState.tsx",
  RadarLoader: "components/ui/RadarLoader.tsx",
  BottomSheet: "components/mobile/BottomSheet.tsx",
  MobileEventInspector: "components/mobile/MobileEventInspector.tsx",
  MobileMapControls: "components/mobile/MobileMapControls.tsx",
  MobileLayerBrowser: "components/mobile/MobileLayerBrowser.tsx",
  RuleBuilderClient: "components/rule-builder/RuleBuilderClient.tsx",
};

// ── Install guide ─────────────────────────────────────────────────────────────

/**
 * Step-by-step notes for initialising shadcn/ui in a new workspace.
 * Run these from apps/web/.
 *
 * 1. Init shadcn:
 *      npx shadcn-ui@latest init
 *    Answers:
 *      - Style: Default
 *      - Base color: Slate  (overridden by our token layer in globals.css)
 *      - CSS variables: Yes
 *      - Tailwind config path: tailwind.config.ts
 *      - Components path: ./src/components/ui
 *      - Utility lib path: ./src/lib/utils.ts
 *      - RSC support: Yes (Next.js 15 app dir)
 *
 * 2. Install all components at once:
 *      npx shadcn-ui@latest add button card dialog dropdown-menu input select \
 *        sheet tabs tooltip badge avatar skeleton progress separator scroll-area \
 *        popover command label switch slider checkbox radio-group toggle \
 *        toggle-group alert alert-dialog toast sonner table
 *
 * 3. Keep components in components/ui/ (generated) and components/<domain>/ (custom).
 *    Never edit generated components directly — instead wrap them.
 *
 * 4. Custom design tokens override the shadcn CSS variables in:
 *      apps/web/src/app/globals.css  (--background, --foreground, --brand-*, etc.)
 *
 * 5. All components must honour:
 *      - @media (prefers-reduced-motion: reduce)  → no transitions / animations
 *      - @media (forced-colors: active)           → high-contrast Windows mode
 *      - RTL: use logical CSS properties (margin-inline-start, not margin-left)
 */
export const INSTALL_GUIDE = `
shadcn/ui + Radix primitives — Aegis Lens setup
================================================

1. From apps/web/:
   npx shadcn-ui@latest init

2. Add all components:
   npx shadcn-ui@latest add ${SHADCN_COMPONENTS.join(" ")}

3. Tailwind config already has design tokens via packages/ui/tailwind-preset.ts.
   The shadcn init will extend, not replace, the existing config.

4. Custom overrides live in:
   - apps/web/src/app/globals.css       (CSS custom properties)
   - packages/ui/tailwind-preset.ts     (Tailwind tokens)
   - apps/web/src/lib/design/           (this directory)

5. To add a new Radix primitive directly (without shadcn wrapper):
   pnpm add @radix-ui/react-<primitive> --filter=web
   Then register it in RADIX_PRIMITIVES_USED and ComponentRegistry above.
`.trim();

// ── Accessibility contract ────────────────────────────────────────────────────

/**
 * Every component in ComponentRegistry must satisfy:
 *
 * Keyboard:
 *   - All interactive elements reachable by Tab (positive tabIndex only if necessary)
 *   - Modal / Dialog: focus trapped inside; Escape closes; focus returns on close
 *   - Dropdown / Menu: Arrow Up/Down navigate; Enter/Space select; Escape closes
 *   - Tooltip: accessible via keyboard focus (not hover-only)
 *
 * ARIA:
 *   - role, aria-label / aria-labelledby, aria-describedby on every widget
 *   - aria-live="polite" on status updates; aria-live="assertive" for critical alerts
 *   - aria-expanded, aria-haspopup on triggers; aria-selected in listboxes
 *
 * Contrast:
 *   - All text: minimum 4.5:1 against background (AA normal)
 *   - Large text (≥18pt / 14pt bold): minimum 3:1 (AA large)
 *   - UI components and focus indicators: minimum 3:1
 *
 * Motion:
 *   - All CSS transitions / animations wrapped in:
 *     @media (prefers-reduced-motion: no-preference) { ... }
 *
 * Pointer:
 *   - Minimum tap target 44×44px on mobile (48×48px for critical actions)
 *   - No hover-only affordances (every hover behaviour has a focus equivalent)
 */
export const ACCESSIBILITY_CONTRACT = "WCAG 2.2 AA + keyboard nav on every component";
