/**
 * Synthetic (TTS) voice detection for audio and video tracks.
 *
 * Analyses prosody, formant patterns, spectral gaps, and background-noise
 * absence to flag likely AI-generated speech. Used to detect propaganda
 * narration generated by TTS systems.
 *
 * NOTES:
 * 1. NVIDIA NeMo (EN): NVIDIA NeMo TTS detection model — primary production detector.
 *    NVIDIA NeMo (UK): Модель виявлення TTS NVIDIA NeMo — основний детектор у production.
 * 2. Resemble Detect (EN): Resemble Detect API — commercial alternative with REST interface.
 *    Resemble Detect (UK): API Resemble Detect — комерційна альтернатива з REST-інтерфейсом.
 * 3. Frequency artifacts (EN): synthetic voices lack natural formant jitter and show spectral gaps.
 *    Frequency artifacts (UK): синтетичні голоси позбавлені природного форматного тремтіння і мають спектральні прогалини.
 */

export type SyntheticVoiceArtifact =
  | "prosody_flatness"       // unnatural monotone pitch / rhythm
  | "formant_anomaly"        // formant transitions too smooth or absent
  | "spectral_gap"           // unexplained silence bands in spectrogram
  | "background_noise_absent"; // unnaturally clean audio — no room tone

export interface SyntheticVoiceResult {
  audioUrl: string;
  isLikelySynthetic: boolean;
  /** 0–1 confidence that the voice IS synthetic */
  confidence: number;
  /** Name/version of the TTS model if identified */
  model?: string;
  artifacts: SyntheticVoiceArtifact[];
  analyzedAt: string;
}

// ── Bilingual notes ───────────────────────────────────────────────────────────

export const SYNTHETIC_VOICE_NOTES_EN = [
  "NVIDIA NeMo TTS detection: GPU-backed model classifies speech as human vs synthetic with per-segment granularity.",
  "Resemble Detect: commercial REST API alternative that returns a deepfake confidence score per audio segment.",
  "Frequency artifacts: synthetic voices typically show prosody flatness, smooth formant transitions, and absent room tone.",
] as const;

export const SYNTHETIC_VOICE_NOTES_UK = [
  "NVIDIA NeMo TTS detection: GPU-модель класифікує мовлення як людське або синтетичне з гранулярністю до сегмента.",
  "Resemble Detect: комерційний REST API, що повертає оцінку deepfake для кожного аудіосегмента.",
  "Частотні артефакти: синтетичні голоси зазвичай мають пласку просодію, гладкі форматні переходи та відсутність шуму приміщення.",
] as const;

// ── Stub detector ─────────────────────────────────────────────────────────────

class SyntheticVoiceDetector {
  private readonly artifactWeights: Record<SyntheticVoiceArtifact, number> = {
    prosody_flatness: 0.35,
    formant_anomaly: 0.30,
    spectral_gap: 0.20,
    background_noise_absent: 0.20,
  };

  /**
   * Stub: returns a clean result with no artifacts.
   * Replace with HTTP call to NVIDIA NeMo or Resemble Detect in production.
   */
  async analyze(audioUrl: string): Promise<SyntheticVoiceResult> {
    return {
      audioUrl,
      isLikelySynthetic: false,
      confidence: 0,
      artifacts: [],
      analyzedAt: new Date().toISOString(),
    };
  }

  /** Derive confidence + verdict from a set of detected artifacts. */
  scoreArtifacts(
    artifacts: SyntheticVoiceArtifact[],
  ): { confidence: number; isLikelySynthetic: boolean } {
    const confidence = Math.min(
      1,
      artifacts.reduce((sum, a) => sum + this.artifactWeights[a], 0),
    );
    return { confidence, isLikelySynthetic: confidence >= 0.5 };
  }
}

export const syntheticVoiceDetector = new SyntheticVoiceDetector();
