/**
 * Plugin SDK — CLI scaffold configuration.
 *
 * Defines the four canonical plugin starter templates used by
 * `npx create-aegis-plugin`. Each template ships a minimal TypeScript
 * project with manifest, types, and a sandbox-compatible entry point.
 *
 * Чотири стартові шаблони для `npx create-aegis-plugin`.
 * Кожен містить TypeScript-проєкт із маніфестом і точкою входу для sandbox.
 */

// ── CLI command constant ──────────────────────────────────────────────────────

/**
 * The npx command users run to scaffold a new plugin.
 *
 * Команда для створення нового плагіну через npx.
 */
export const CLI_SCAFFOLD_CMD = "npx create-aegis-plugin" as const;

// ── ScaffoldTemplate ──────────────────────────────────────────────────────────

export type ScaffoldTemplateId = "data-layer" | "widget" | "ai-tool" | "exporter";

/**
 * Configuration for a single scaffold template.
 *
 * Конфігурація одного шаблону для scaffold.
 */
export interface ScaffoldTemplate {
  id: ScaffoldTemplateId;
  /** Human-readable label shown in the interactive CLI picker */
  label_en: string;
  label_uk: string;
  description_en: string;
  description_uk: string;
  /**
   * Files generated by this template (relative to project root).
   * Listed here for documentation / IDE preview purposes.
   *
   * Файли, які генерує цей шаблон (відносно кореня проєкту).
   */
  generatedFiles: string[];
  /** Required peer packages installed by the scaffold */
  peerDeps: string[];
  /** NPM package name that backs this template */
  templatePackage: string;
}

// ── Template definitions ──────────────────────────────────────────────────────

const SCAFFOLD_TEMPLATES: Record<ScaffoldTemplateId, ScaffoldTemplate> = {
  "data-layer": {
    id: "data-layer",
    label_en: "Data Layer",
    label_uk: "Шар даних",
    description_en: "Adds a custom GeoJSON / MVT map layer with an optional live data feed.",
    description_uk: "Додає власний шар GeoJSON/MVT із підтримкою live-оновлень.",
    generatedFiles: [
      "manifest.ts",
      "src/layer.ts",
      "src/source.ts",
      "src/style.ts",
      "README.md",
    ],
    peerDeps: ["@aegis/plugin-sdk", "maplibre-gl"],
    templatePackage: "create-aegis-plugin-data-layer",
  },

  widget: {
    id: "widget",
    label_en: "Dashboard Widget",
    label_uk: "Віджет дашборду",
    description_en: "Adds a resizable dashboard widget rendered in a sandboxed iframe.",
    description_uk: "Додає адаптивний віджет у iframe-пісочниці на дашборді.",
    generatedFiles: [
      "manifest.ts",
      "src/widget.tsx",
      "src/bridge.ts",
      "public/widget.html",
      "README.md",
    ],
    peerDeps: ["@aegis/plugin-sdk", "react", "react-dom"],
    templatePackage: "create-aegis-plugin-widget",
  },

  "ai-tool": {
    id: "ai-tool",
    label_en: "AI Tool (Copilot Extension)",
    label_uk: "AI-інструмент (розширення Copilot)",
    description_en: "Extends the Aegis Lens copilot with a new structured tool.",
    description_uk: "Додає новий структурований інструмент до копілота Aegis Lens.",
    generatedFiles: [
      "manifest.ts",
      "src/tool-definition.ts",
      "src/handler.ts",
      "src/schema.ts",
      "README.md",
    ],
    peerDeps: ["@aegis/plugin-sdk", "zod"],
    templatePackage: "create-aegis-plugin-ai-tool",
  },

  exporter: {
    id: "exporter",
    label_en: "Exporter",
    label_uk: "Експортер",
    description_en: "Adds a new export format (CSV variant, XLSX, custom JSON schema, etc.).",
    description_uk: "Додає новий формат експорту (CSV-варіант, XLSX, власна схема JSON тощо).",
    generatedFiles: [
      "manifest.ts",
      "src/exporter.ts",
      "src/formatter.ts",
      "README.md",
    ],
    peerDeps: ["@aegis/plugin-sdk"],
    templatePackage: "create-aegis-plugin-exporter",
  },
};

// ── getScaffoldConfig ─────────────────────────────────────────────────────────

/**
 * Return the scaffold configuration for a given template ID.
 * Throws if an unknown template ID is provided.
 *
 * Повертає конфігурацію шаблону або кидає помилку для невідомого ID.
 */
export function getScaffoldConfig(template: ScaffoldTemplateId): ScaffoldTemplate {
  const config = SCAFFOLD_TEMPLATES[template];
  if (!config) {
    throw new Error(
      `[cli-scaffold] Unknown template "${template}". ` +
        `Valid options: ${Object.keys(SCAFFOLD_TEMPLATES).join(", ")}`,
    );
  }
  return config;
}

/** All available scaffold templates as an ordered array. */
export const ALL_SCAFFOLD_TEMPLATES: ScaffoldTemplate[] = Object.values(SCAFFOLD_TEMPLATES);
