/**
 * Directory seed — companies + tools.
 * Sprint 1.1 placeholder. Sprint 2: DB + claim flow.
 */

export type DirectoryEntry = {
  slug: string;
  name: string;
  category: string;
  region: string;
  /** HQ city — optional. Used for /companies/<city> + /industries/<industry>/<city> intersect pages. */
  city?: string;
  description: string;
  verified: boolean;
};

export const COMPANIES: DirectoryEntry[] = [
  {
    slug: "demo-osint-co",
    name: "Demo OSINT Co",
    category: "OSINT",
    region: "EU",
    description: "Placeholder OSINT firm. Directory wires up real listings in Sprint 2.",
    verified: false,
  },
  {
    slug: "demo-cyber-llc",
    name: "Demo Cyber LLC",
    category: "Cybersecurity",
    region: "US",
    description: "Placeholder threat-intel boutique.",
    verified: false,
  },
  {
    slug: "demo-geo-int",
    name: "Demo GeoInt",
    category: "Geospatial",
    region: "UA",
    description: "Placeholder geospatial analytics firm.",
    verified: false,
  },
  {
    slug: "anduril",
    name: "Anduril Industries",
    category: "Defense Tech",
    region: "US",
    city: "Costa Mesa",
    description: "Defense technology company building autonomous systems, Lattice OS, and Ghost/Altius UAVs.",
    verified: false,
  },
  {
    slug: "palantir",
    name: "Palantir Technologies",
    category: "Defense Tech",
    region: "US",
    city: "Denver",
    description: "Data integration and analytics platforms (Gotham, Foundry, AIP) used by defense and intel agencies.",
    verified: false,
  },
  {
    slug: "helsing",
    name: "Helsing",
    category: "Defense Tech",
    region: "EU",
    city: "Munich",
    description: "European AI defense company providing battlefield software and autonomous systems for NATO partners.",
    verified: false,
  },
  {
    slug: "rheinmetall",
    name: "Rheinmetall",
    category: "Defense Tech",
    region: "EU",
    city: "Düsseldorf",
    description: "German defense contractor producing tanks, IFVs, ammunition, and air-defense systems for Ukraine and NATO.",
    verified: false,
  },
  {
    slug: "saab-group",
    name: "Saab Group",
    category: "Defense Tech",
    region: "EU",
    city: "Stockholm",
    description: "Swedish defense and security company producing Gripen fighters, GlobalEye, NLAW, and Carl-Gustaf.",
    verified: false,
  },
  {
    slug: "lockheed-martin",
    name: "Lockheed Martin",
    category: "Defense Tech",
    region: "US",
    city: "Bethesda",
    description: "US defense prime contractor producing F-35, HIMARS, PAC-3, and ATACMS.",
    verified: false,
  },
  {
    slug: "northrop-grumman",
    name: "Northrop Grumman",
    category: "Defense Tech",
    region: "US",
    city: "Falls Church",
    description: "US defense and aerospace company producing B-21, Global Hawk, and IBCS air-defense C2.",
    verified: false,
  },
  {
    slug: "raytheon",
    name: "Raytheon (RTX)",
    category: "Defense Tech",
    region: "US",
    city: "Arlington",
    description: "US defense contractor producing Patriot, NASAMS missiles, Stinger, and Tomahawk.",
    verified: false,
  },
  {
    slug: "bellingcat",
    name: "Bellingcat",
    category: "OSINT",
    region: "EU",
    city: "Amsterdam",
    description: "Investigative journalism collective specializing in OSINT, geolocation, and conflict verification.",
    verified: false,
  },
  {
    slug: "janes",
    name: "Janes",
    category: "OSINT",
    region: "UK",
    city: "London",
    description: "Defense and security intelligence provider with extensive open-source databases on equipment and forces.",
    verified: false,
  },
  {
    slug: "recorded-future",
    name: "Recorded Future",
    category: "Threat Intelligence",
    region: "US",
    city: "Boston",
    description: "Threat intelligence platform combining OSINT, dark-web, and technical sources for security teams.",
    verified: false,
  },
  {
    slug: "sayari",
    name: "Sayari",
    category: "OSINT",
    region: "US",
    city: "Washington",
    description: "Commercial OSINT and corporate-graph platform for sanctions, supply-chain, and risk research.",
    verified: false,
  },
  {
    slug: "maxar-technologies",
    name: "Maxar Technologies",
    category: "Satellite Imagery",
    region: "US",
    city: "Westminster",
    description: "Commercial satellite operator providing high-resolution imagery widely used in Ukraine war reporting.",
    verified: false,
  },
  {
    slug: "planet-labs",
    name: "Planet Labs",
    category: "Satellite Imagery",
    region: "US",
    city: "San Francisco",
    description: "Operator of the world's largest constellation of Earth-imaging satellites with daily global revisit.",
    verified: false,
  },
  {
    slug: "blacksky",
    name: "BlackSky",
    category: "Satellite Imagery",
    region: "US",
    city: "Herndon",
    description: "Real-time geospatial intelligence company with a high-revisit smallsat constellation.",
    verified: false,
  },
  {
    slug: "ukroboronprom",
    name: "Ukroboronprom",
    category: "Defense Tech",
    region: "UA",
    city: "Kyiv",
    description: "Ukrainian state defense industry conglomerate producing armored vehicles, aircraft, and munitions.",
    verified: false,
  },
  {
    slug: "antonov",
    name: "Antonov",
    category: "Aerospace",
    region: "UA",
    city: "Kyiv",
    description: "Ukrainian aircraft manufacturer known for An-series transport aircraft including the An-225 Mriya.",
    verified: false,
  },
  {
    slug: "motor-sich",
    name: "Motor Sich",
    category: "Aerospace",
    region: "UA",
    city: "Zaporizhzhia",
    description: "Ukrainian manufacturer of aircraft engines, helicopter powerplants, and gas-turbine units.",
    verified: false,
  },
  {
    slug: "kvertus",
    name: "Kvertus",
    category: "Defense Tech",
    region: "UA",
    city: "Kyiv",
    description: "Ukrainian electronic-warfare manufacturer producing counter-UAV jammers and EW systems for the front.",
    verified: false,
  },
  {
    slug: "tytan-defense-ua",
    name: "Tytan Defense UA",
    category: "Defense Tech",
    region: "UA",
    city: "Kyiv",
    description: "Ukrainian defense manufacturer producing UGVs and unmanned ground systems for combat support.",
    verified: false,
  },
  {
    slug: "mandiant",
    name: "Mandiant",
    category: "Cybersecurity",
    region: "US",
    city: "Reston",
    description: "Cyber threat intelligence and incident response firm (now part of Google Cloud).",
    verified: false,
  },
  {
    slug: "crowdstrike",
    name: "CrowdStrike",
    category: "Cybersecurity",
    region: "US",
    city: "Austin",
    description: "Endpoint security and threat intelligence platform tracking nation-state and criminal actors.",
    verified: false,
  },
  {
    slug: "microsoft-threat-intel",
    name: "Microsoft Threat Intelligence",
    category: "Cybersecurity",
    region: "US",
    city: "Redmond",
    description: "Microsoft's threat-intel division publishing reporting on state-aligned actors targeting Ukraine and partners.",
    verified: false,
  },
];

export const TOOLS: DirectoryEntry[] = [
  {
    slug: "demo-imagery-search",
    name: "Demo Imagery Search",
    category: "Verification",
    region: "—",
    description: "Placeholder reverse-image-search tool.",
    verified: false,
  },
  {
    slug: "demo-sat-monitor",
    name: "Demo Sat Monitor",
    category: "Satellite",
    region: "—",
    description: "Placeholder satellite-monitoring SaaS.",
    verified: false,
  },
  {
    slug: "demo-osint-toolkit",
    name: "Demo OSINT Toolkit",
    category: "OSINT",
    region: "—",
    description: "Placeholder all-in-one OSINT toolkit.",
    verified: false,
  },
  {
    slug: "bellingcat-toolkit",
    name: "Bellingcat Online Investigation Toolkit",
    category: "OSINT",
    region: "—",
    description: "Curated public list of OSINT tools, methods, and resources maintained by Bellingcat.",
    verified: false,
  },
  {
    slug: "openstreetmap",
    name: "OpenStreetMap",
    category: "Mapping",
    region: "—",
    description: "Free, editable map of the world widely used for geolocation, basemaps, and humanitarian mapping.",
    verified: false,
  },
  {
    slug: "sentinel-hub",
    name: "Sentinel Hub",
    category: "Satellite",
    region: "—",
    description: "Cloud platform for searching and processing Sentinel and Landsat imagery via APIs and EO Browser.",
    verified: false,
  },
  {
    slug: "google-earth-engine",
    name: "Google Earth Engine",
    category: "Satellite",
    region: "—",
    description: "Cloud-based geospatial analysis platform for petabyte-scale satellite imagery and remote-sensing datasets.",
    verified: false,
  },
  {
    slug: "mapillary",
    name: "Mapillary",
    category: "Street-level Imagery",
    region: "—",
    description: "Crowdsourced street-level imagery platform used by OSINT researchers for ground-truth geolocation.",
    verified: false,
  },
  {
    slug: "hunchly",
    name: "Hunchly",
    category: "Verification",
    region: "—",
    description: "Web-capture and case-management tool that automatically preserves evidence pages during investigations.",
    verified: false,
  },
  {
    slug: "maltego",
    name: "Maltego",
    category: "OSINT",
    region: "—",
    description: "Link-analysis and graph visualization tool for mapping relationships across people, infrastructure, and data.",
    verified: false,
  },
  {
    slug: "spiderfoot",
    name: "SpiderFoot",
    category: "OSINT",
    region: "—",
    description: "Open-source OSINT automation tool that integrates with 200+ data sources for footprinting and recon.",
    verified: false,
  },
  {
    slug: "yandex-reverse-image",
    name: "Yandex Reverse Image",
    category: "Verification",
    region: "—",
    description: "Russian search-engine reverse image tool widely valued by OSINT researchers for facial and landmark matches.",
    verified: false,
  },
  {
    slug: "tineye",
    name: "TinEye",
    category: "Verification",
    region: "—",
    description: "Reverse image search engine focused on finding earlier occurrences and modified versions of an image.",
    verified: false,
  },
  {
    slug: "foca",
    name: "FOCA",
    category: "OSINT",
    region: "—",
    description: "Metadata and document-analysis tool that extracts hidden information from public documents.",
    verified: false,
  },
  {
    slug: "exiftool",
    name: "ExifTool",
    category: "Verification",
    region: "—",
    description: "Open-source command-line tool to read, write, and edit metadata in images, video, and documents.",
    verified: false,
  },
  {
    slug: "wayback-machine",
    name: "Wayback Machine",
    category: "Archive",
    region: "—",
    description: "Internet Archive web-archive service used to retrieve historical snapshots of webpages.",
    verified: false,
  },
  {
    slug: "telegram-webhooks",
    name: "Telegram Webhooks",
    category: "Collection",
    region: "—",
    description: "Telegram Bot API webhook mechanism used to ingest public channel messages for monitoring pipelines.",
    verified: false,
  },
  {
    slug: "twint",
    name: "Twint",
    category: "OSINT",
    region: "—",
    description: "Open-source Twitter scraping tool (legacy) for collecting tweets without API limits.",
    verified: false,
  },
  {
    slug: "ais-explorer",
    name: "AIS-EXPLORER",
    category: "Maritime",
    region: "—",
    description: "Open AIS vessel tracking platform for monitoring shipping movements and dark-fleet activity.",
    verified: false,
  },
  {
    slug: "flightradar24",
    name: "FlightRadar24",
    category: "Aviation",
    region: "—",
    description: "Real-time global flight tracking platform widely used to monitor military and civilian air activity.",
    verified: false,
  },
  {
    slug: "academic-torrents",
    name: "Academic Torrents",
    category: "Datasets",
    region: "—",
    description: "Distributed repository for sharing large research datasets via BitTorrent.",
    verified: false,
  },
  {
    slug: "opencorporates",
    name: "OpenCorporates",
    category: "Corporate Data",
    region: "—",
    description: "Largest open database of companies worldwide; used in sanctions and corporate-network investigations.",
    verified: false,
  },
  {
    slug: "icij-offshoreleaks",
    name: "ICIJ OffshoreLeaks",
    category: "Corporate Data",
    region: "—",
    description: "ICIJ's searchable database of offshore entities from Panama Papers, Pandora Papers, and related leaks.",
    verified: false,
  },
  {
    slug: "citizenlab",
    name: "Citizen Lab",
    category: "Research",
    region: "CA",
    description: "Interdisciplinary research lab at U. Toronto investigating digital espionage, censorship, and human rights.",
    verified: false,
  },
  {
    slug: "dataminr",
    name: "Dataminr",
    category: "Social Media Intelligence",
    region: "US",
    city: "New York",
    description: "AI-powered real-time event detection platform that surfaces breaking news and risk signals from public data streams including social media.",
    verified: false,
  },
  {
    slug: "liveuamap",
    name: "LiveUAMap",
    category: "OSINT",
    region: "UA",
    description: "Ukraine-focused real-time conflict map aggregating social media and official sources into a live event feed.",
    verified: false,
  },
];
