/**
 * Helper utilities for generating OG image URLs served by /api/og.
 *
 * Usage:
 *   import { getOGImageUrl } from "@/lib/og-image";
 *   const url = getOGImageUrl("event", { id: "01HX...", class: "military_action" });
 *   const url = getOGImageUrl("region", { name: "Kharkiv", events: "18" });
 *   const url = getOGImageUrl("report", { title: "Weekly Brief", date: "2026-06-03" });
 */

export type OGImageType = "default" | "event" | "region" | "report" | "blog";

/**
 * Build the URL for a dynamic OG image generated by /api/og.
 *
 * @param type  The variant of OG image to render.
 * @param params  Additional query parameters forwarded to the route (title, subtitle, id, etc.).
 */
export function getOGImageUrl(
  type: OGImageType,
  params: Record<string, string> = {},
): string {
  const base = "/api/og";
  const sp = new URLSearchParams({ type, ...params });
  return `${base}?${sp.toString()}`;
}

/**
 * Convenience wrappers for the most common OG image variants.
 */
export const ogImages = {
  default: (title?: string, subtitle?: string) =>
    getOGImageUrl("default", {
      ...(title ? { title } : {}),
      ...(subtitle ? { subtitle } : {}),
    }),

  event: (id: string, eventClass?: string, title?: string) =>
    getOGImageUrl("event", {
      id,
      ...(eventClass ? { class: eventClass } : {}),
      ...(title ? { title } : {}),
    }),

  region: (name: string, events?: string | number) =>
    getOGImageUrl("region", {
      name,
      ...(events !== undefined ? { events: String(events) } : {}),
    }),

  report: (title: string, date?: string) =>
    getOGImageUrl("report", {
      title,
      ...(date ? { date } : {}),
    }),

  blog: (title: string, subtitle?: string) =>
    getOGImageUrl("blog", {
      title,
      ...(subtitle ? { subtitle } : {}),
    }),
};
